"""SCA must parse yarn.lock and Gemfile deps, and must never report coverage
'complete' when a dependency manifest present in the tree was left unresolved
(e.g. a Gemfile without a Gemfile.lock). Regression for a tree reporting
'complete' 1/1 while a 100+ pkg yarn.lock and a multi-gem Gemfile sat unparsed.
"""
from __future__ import annotations

import os
import sys
import tempfile

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))

from narvy import main
from narvy.sca import web_deps


def _write(root, rel, content):
    p = os.path.join(root, rel)
    os.makedirs(os.path.dirname(p) or root, exist_ok=True)
    with open(p, "w", encoding="utf-8") as f:
        f.write(content)


_YARN_LOCK = '''# THIS IS AN AUTOGENERATED FILE.
# yarn lockfile v1

"@babel/code-frame@^7.0.0":
  version "7.26.2"
  resolved "https://registry.yarnpkg.com/@babel/code-frame/-/x.tgz"
  dependencies:
    js-tokens "^4.0.0"

lodash@^4.17.0, lodash@^4.17.21:
  version "4.17.21"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz"
'''


def test_yarn_lock_parsed():
    with tempfile.TemporaryDirectory() as root:
        _write(root, "yarn.lock", _YARN_LOCK)
        _write(root, "package.json", '{"name":"x","dependencies":{}}')
        deps = web_deps.collect_dependencies(root)
        pairs = {(d.name, d.version) for d in deps}
        assert ("@babel/code-frame", "7.26.2") in pairs
        assert ("lodash", "4.17.21") in pairs
        # yarn.lock is authoritative for the npm ecosystem.
        assert all(d.source == "yarn.lock" for d in deps if d.ecosystem == "npm")


def test_gemfile_exact_pins_parsed_ranges_skipped():
    with tempfile.TemporaryDirectory() as root:
        _write(root, "Gemfile",
               "source 'https://rubygems.org'\n"
               "gem 'rails', '8.1.3.1'\n"      # exact -> parsed
               "gem 'rouge', '~> 5.0'\n"       # range -> skipped
               "gem 'marcel'\n")               # unversioned -> skipped
        deps = web_deps.collect_dependencies(root)
        gems = {(d.name, d.version) for d in deps if d.ecosystem == "RubyGems"}
        assert gems == {("rails", "8.1.3.1")}


def test_gemfile_without_lock_is_partial_not_complete():
    with tempfile.TemporaryDirectory() as root:
        _write(root, "Gemfile", "source 'x'\ngem 'rails', '8.1.3.1'\ngem 'rouge', '~> 5.0'\n")
        deps = web_deps.collect_dependencies(root)
        gaps = web_deps._coverage_gaps(root, deps)
        assert any("Gemfile-without-lock" in g for g in gaps)
        cov = main._sca_coverage({
            "unique_dependencies_detected": len(deps),
            "unique_dependencies_checked": len(deps),
            "unparsed_manifests": gaps,
        })
        assert cov["status"] == "partial"
        assert "unparsed_manifest" in cov["degraded_reasons"]


def test_all_manifests_resolved_stays_complete():
    with tempfile.TemporaryDirectory() as root:
        _write(root, "yarn.lock", _YARN_LOCK)
        deps = web_deps.collect_dependencies(root)
        gaps = web_deps._coverage_gaps(root, deps)
        assert gaps == []
        cov = main._sca_coverage({
            "unique_dependencies_detected": len(deps),
            "unique_dependencies_checked": len(deps),
            "unparsed_manifests": gaps,
        })
        assert cov["status"] == "complete"
